# -*- coding: utf-8 -*-
"""Base_ipywidgets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DlKIaZaqmX7vhuaIq4NIs5FaaPyv9FC5
"""

#@title Prototipo
# ---------------------------------------------------------------
#                    Librerías
# ---------------------------------------------------------------
import ipywidgets as widgets #controles para GUI
import io #manejo de archivos
from ipywidgets import FileUpload #subir archivos desde local
from IPython.display import display #mostrar controles
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
np.random.seed(100)
x = np.random.rand(10)
y = np.random.rand(10)

# ---------------------------------------------------------------
#               Variables Globales
# ---------------------------------------------------------------
nom_archivo = '' #nombre de archivo del dataset
df = None #dataset

# ---------------------------------------------------------------
#             Componentes de Interfaz Gráfica
# ---------------------------------------------------------------
# ----- Botón: Seleccionar archivo
BOTON_SELECCIONAR_ARCHIVO = FileUpload(description='Seleccionar', button_style='success', accept='csv', multiple=False, icon='Upload' )
# ----- Botón: Cargar archivo
#     button_style = { danger, warning, info, success  }
BOTON_CARGAR_ARCHIVO = widgets.Button(description='Cargar datos', button_style='danger', icon='check')
# ----- Botón: Mostrar Scatter
BOTON_MOSTRAR_SCATTER = widgets.Button(description='Scatterplot', button_style='info', icon='check')

# ----- Texto: Instrucciones acerca del programa
INSTRUCCIONES_DEL_PROGRAMA = widgets.HTML("""
        <h1>Prototipo X: Detección de Patrones ... a partir de Texto para Exportación del Espárrago
        </h1>
        <h2>Integrantes:</h2>
        <ul>
          <li>Juan Pérez</li>
          <li>Karla Sánchez</li>
          <li>Manuel García</li>
        </ul>
  """)

# ----- Texto: Instrucciones acerca del programa
INSTRUCCIONES_PESTANA1 = widgets.HTML("""
        <h3>Instrucciones:</h3>
        Ubica el dataset desde en la ruta de computadora y súbelo.
        Asegúrate de tenerlo en formato CSV.
  """)

# ----- Texto: Instrucciones acerca del programa
INSTRUCCIONES_PESTANA2 = widgets.HTML("""
        <h3>Instrucciones:</h3>
        En esta pestaña podrás ver gráficos a partir del dataset cargado.
  """)

# ----- Función para construir pestañas
def construir_pestanas():
  pestanas_programa = widgets.Tab()

  #los componentes que irían en cada pestaña
  cont_pestana1 = widgets.VBox([INSTRUCCIONES_PESTANA1, BOTON_SELECCIONAR_ARCHIVO, BOTON_CARGAR_ARCHIVO])
  cont_pestana2 = widgets.VBox([INSTRUCCIONES_PESTANA2, BOTON_MOSTRAR_SCATTER])
  contenido_cada_pestana = [cont_pestana1, cont_pestana2]
  #ingresamos los componentes para cada pestaña
  pestanas_programa.children = contenido_cada_pestana

  #los nombres de cada pestaña

  tab_contenidos = ['Seleccionar', 'Cargar']
  for i in range(len(contenido_cada_pestana)):
    pestanas_programa.set_title(i, tab_contenidos[i])
  return pestanas_programa


def construir_pestanas_con_graf(x):
  pestanas_programa = widgets.Tab()

  #los componentes que irían en cada pestaña
  cont_pestana1 = widgets.VBox([INSTRUCCIONES_PESTANA1, BOTON_SELECCIONAR_ARCHIVO, BOTON_CARGAR_ARCHIVO])
  cont_pestana2 = widgets.VBox([INSTRUCCIONES_PESTANA2, BOTON_MOSTRAR_SCATTER, x])
  contenido_cada_pestana = [cont_pestana1, cont_pestana2]
  #ingresamos los componentes para cada pestaña
  pestanas_programa.children = contenido_cada_pestana

  #los nombres de cada pestaña

  tab_contenidos = ['Seleccionar', 'Cargar']
  for i in range(len(contenido_cada_pestana)):
    pestanas_programa.set_title(i, tab_contenidos[i])
  return pestanas_programa

# ----- Pestañas: son 2 pestañas cada una conteniendo un botón
PESTANAS_DEL_PROGRAMA = construir_pestanas()



# ---------------------------------------------------------------
#             Gestión de Eventos
# ---------------------------------------------------------------
# --- Evento: cuando alguien hace click en el botón "Cargar archivo"
def evento_click_cargar_archivo(b):
  global nom_archivo, df
  # Leer archivo CSV y lo transforma a DataFrame
  def leerArchivoCSV(x, nom_arch):
    return pd.read_csv(io.BytesIO(x.value[nom_arch]['content']))
  #Captura del nombre del archivo
  nom_archivo = next(iter(BOTON_SELECCIONAR_ARCHIVO.value))
  # Obtenemos el dataframe
  df = leerArchivoCSV(BOTON_SELECCIONAR_ARCHIVO, nom_archivo)

def evento_click_mostrar_scatter(b):
  splot = plt.scatter(x,y)
  display( widgets.VBox(children=[INSTRUCCIONES_DEL_PROGRAMA, construir_pestanas_con_graf(splot)]) )
  #print(splot)

# ---------------------------------------------------------------
#             Asignación de Evento a Componentes GUI
# ---------------------------------------------------------------
BOTON_CARGAR_ARCHIVO.on_click(evento_click_cargar_archivo)
BOTON_MOSTRAR_SCATTER.on_click(evento_click_mostrar_scatter)

# ---------------------------------------------------------------
#             GUI Final
# ---------------------------------------------------------------
def diseno_componentes():
  display( widgets.VBox(children=[INSTRUCCIONES_DEL_PROGRAMA, PESTANAS_DEL_PROGRAMA]) )

# ---------------------------------------------------------------
#             Lanzamiento de la aplicación
# ---------------------------------------------------------------
diseno_componentes()

